// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

export enum TransferState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    StatePending = 0,
    StateTransferring = 1,
    StatePaused = 2,
    StateCompleted = 3,
    StateFailed = 4,
    StateCancelled = 5,
};

export class TransferTask {
    "id": string;
    "type": TransferType;
    "state": TransferState;
    "file_name": string;
    "file_size": number;
    "peer_id": string;
    "peer_name": string;
    "bytes_transferred": number;
    "speed": number;
    "file_md5": string;
    "chunks_total": number;
    "chunks_completed": number;
    "created_at": time$0.Time;
    "completed_at": time$0.Time | null;

    /** Creates a new TransferTask instance. */
    constructor($$source: Partial<TransferTask> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = TransferType.$zero;
        }
        if (!("state" in $$source)) {
            this["state"] = TransferState.$zero;
        }
        if (!("file_name" in $$source)) {
            this["file_name"] = "";
        }
        if (!("file_size" in $$source)) {
            this["file_size"] = 0;
        }
        if (!("peer_id" in $$source)) {
            this["peer_id"] = "";
        }
        if (!("peer_name" in $$source)) {
            this["peer_name"] = "";
        }
        if (!("bytes_transferred" in $$source)) {
            this["bytes_transferred"] = 0;
        }
        if (!("speed" in $$source)) {
            this["speed"] = 0;
        }
        if (!("file_md5" in $$source)) {
            this["file_md5"] = "";
        }
        if (!("chunks_total" in $$source)) {
            this["chunks_total"] = 0;
        }
        if (!("chunks_completed" in $$source)) {
            this["chunks_completed"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }
        if (!("completed_at" in $$source)) {
            this["completed_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TransferTask instance from a string or object.
     */
    static createFrom($$source: any = {}): TransferTask {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TransferTask($$parsedSource as Partial<TransferTask>);
    }
}

export enum TransferType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    TypeSend = 0,
    TypeReceive = 1,
};
