// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

/**
 * @readonly
 * @enum {number}
 */
export const TransferState = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: 0,

    StatePending: 0,
    StateTransferring: 1,
    StatePaused: 2,
    StateCompleted: 3,
    StateFailed: 4,
    StateCancelled: 5,
};

export class TransferTask {
    /**
     * Creates a new TransferTask instance.
     * @param {Partial<TransferTask>} [$$source = {}] - The source object to create the TransferTask.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {TransferType}
             */
            this["type"] = TransferType.$zero;
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {TransferState}
             */
            this["state"] = TransferState.$zero;
        }
        if (!("file_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["file_name"] = "";
        }
        if (!("file_size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["file_size"] = 0;
        }
        if (!("peer_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["peer_id"] = "";
        }
        if (!("peer_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["peer_name"] = "";
        }
        if (!("bytes_transferred" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bytes_transferred"] = 0;
        }
        if (!("speed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["speed"] = 0;
        }
        if (!("file_md5" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["file_md5"] = "";
        }
        if (!("chunks_total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["chunks_total"] = 0;
        }
        if (!("chunks_completed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["chunks_completed"] = 0;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["created_at"] = null;
        }
        if (!("completed_at" in $$source)) {
            /**
             * @member
             * @type {time$0.Time | null}
             */
            this["completed_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TransferTask instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TransferTask}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TransferTask(/** @type {Partial<TransferTask>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {number}
 */
export const TransferType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: 0,

    TypeSend: 0,
    TypeReceive: 1,
};
