// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Asset {
    "name": string;
    "browser_download_url": string;
    "size": number;

    /** Creates a new Asset instance. */
    constructor($$source: Partial<Asset> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("browser_download_url" in $$source)) {
            this["browser_download_url"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Asset instance from a string or object.
     */
    static createFrom($$source: any = {}): Asset {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Asset($$parsedSource as Partial<Asset>);
    }
}

export class ReleaseInfo {
    "tag_name": string;
    "body": string;
    "assets": Asset[];

    /** Creates a new ReleaseInfo instance. */
    constructor($$source: Partial<ReleaseInfo> = {}) {
        if (!("tag_name" in $$source)) {
            this["tag_name"] = "";
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }
        if (!("assets" in $$source)) {
            this["assets"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReleaseInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ReleaseInfo {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("assets" in $$parsedSource) {
            $$parsedSource["assets"] = $$createField2_0($$parsedSource["assets"]);
        }
        return new ReleaseInfo($$parsedSource as Partial<ReleaseInfo>);
    }
}

// Private type creation functions
const $$createType0 = Asset.createFrom;
const $$createType1 = $Create.Array($$createType0);
