// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CancelDownload(): $CancellablePromise<void> {
    return $Call.ByID(29341022);
}

export function CheckUpdate(): $CancellablePromise<[$models.ReleaseInfo | null, boolean]> {
    return $Call.ByID(148234589).then(($result: any) => {
        $result[0] = $$createType1($result[0]);
        return $result;
    });
}

export function GetVersion(): $CancellablePromise<string> {
    return $Call.ByID(1688220732);
}

export function InstallAndRestart(): $CancellablePromise<void> {
    return $Call.ByID(2100076147);
}

export function OpenReleasePage(): $CancellablePromise<void> {
    return $Call.ByID(3022883594);
}

export function StartDownload(): $CancellablePromise<void> {
    return $Call.ByID(3005101320);
}

// Private type creation functions
const $$createType0 = $models.ReleaseInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
