// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "./internal/model/models.js";

export function CancelTask(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(840985698, taskID);
}

export function ChooseSavePath(fileName: string): $CancellablePromise<string> {
    return $Call.ByID(1072275718, fileName);
}

export function GetDevices(): $CancellablePromise<{ [_ in string]?: any }[]> {
    return $Call.ByID(2647233474).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetLocalInfo(): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(2844631854).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetTasks(): $CancellablePromise<(model$0.TransferTask | null)[]> {
    return $Call.ByID(4294202735).then(($result: any) => {
        return $$createType4($result);
    });
}

export function RespondReceive(taskID: string, accept: boolean, savePath: string): $CancellablePromise<void> {
    return $Call.ByID(1155661195, taskID, accept, savePath);
}

export function SelectAndSend(peerID: string): $CancellablePromise<void> {
    return $Call.ByID(3663064700, peerID);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = model$0.TransferTask.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType3);
