// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "./internal/model/models.js";

/**
 * @param {string} taskID
 * @returns {$CancellablePromise<void>}
 */
export function CancelTask(taskID) {
    return $Call.ByID(840985698, taskID);
}

/**
 * @param {string} fileName
 * @returns {$CancellablePromise<string>}
 */
export function ChooseSavePath(fileName) {
    return $Call.ByID(1072275718, fileName);
}

/**
 * @returns {$CancellablePromise<{ [_ in string]?: any }[]>}
 */
export function GetDevices() {
    return $Call.ByID(2647233474).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetLocalInfo() {
    return $Call.ByID(2844631854).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<(model$0.TransferTask | null)[]>}
 */
export function GetTasks() {
    return $Call.ByID(4294202735).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {string} taskID
 * @param {boolean} accept
 * @param {string} savePath
 * @returns {$CancellablePromise<void>}
 */
export function RespondReceive(taskID, accept, savePath) {
    return $Call.ByID(1155661195, taskID, accept, savePath);
}

/**
 * @param {string} peerID
 * @returns {$CancellablePromise<void>}
 */
export function SelectAndSend(peerID) {
    return $Call.ByID(3663064700, peerID);
}

/**
 * @param {string} peerID
 * @param {string[]} paths
 * @returns {$CancellablePromise<void>}
 */
export function SendPaths(peerID, paths) {
    return $Call.ByID(308551705, peerID, paths);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = model$0.TransferTask.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType3);
