// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelTask(arg1) {
  return window['go']['main']['App']['CancelTask'](arg1);
}

export function GetDevices() {
  return window['go']['main']['App']['GetDevices']();
}

export function GetLocalInfo() {
  return window['go']['main']['App']['GetLocalInfo']();
}

export function GetTasks() {
  return window['go']['main']['App']['GetTasks']();
}

export function RespondReceive(arg1, arg2) {
  return window['go']['main']['App']['RespondReceive'](arg1, arg2);
}

export function SelectAndSend(arg1) {
  return window['go']['main']['App']['SelectAndSend'](arg1);
}
